#!/usr/bin/env python3
"""
Lab Hands-on: Browser Runtime, Network Protocols & Rendering Engine Pipelines
Simulates:
1. Event Loop Mechanics: Call Stack, Microtask Queue (Promises), Macrotask Queue (Timers).
2. Network Resource Pipeline: HTTP/2 Stream Multiplexing & Resource Loader.
3. Rendering Engine Pipeline: HTML/CSS Tokenization -> DOM/CSSOM Construction ->
   Layout (Reflow Geometry) -> Paint (Display List Raster Prep).
"""

from dataclasses import dataclass, field
from enum import Enum, auto
from typing import List, Dict, Optional, Callable, Any
from collections import deque
import time
import sys

# ANSI Color formatting
CLR_RESET   = "\033[0m"
CLR_BOLD    = "\033[1m"
CLR_RED     = "\033[31m"
CLR_GREEN   = "\033[32m"
CLR_YELLOW  = "\033[33m"
CLR_BLUE    = "\033[34m"
CLR_MAGENTA = "\033[35m"
CLR_CYAN    = "\033[36m"
CLR_GRAY    = "\033[90m"

# ============================================================================
# MODULE 1: JAVASCRIPT EVENT LOOP SIMULATOR (WHATWG SPECIFICATION MAPPING)
# ============================================================================

class TaskType(Enum):
    MACRO = auto()   # setTimeout, setInterval, I/O
    MICRO = auto()   # Promise callbacks, queueMicrotask, MutationObserver

@dataclass
class Task:
    name: str
    task_type: TaskType
    action: Callable[[], None]

class EventLoop:
    """
    Simulates WHATWG Browser Event Loop:
    1. Execute synchronous call-stack.
    2. Drain microtask queue entirely before yielding to rendering.
    3. Execute single macrotask from task queue.
    4. Trigger rendering pipeline opportunity.
    """
    def __init__(self):
        self.call_stack: List[str] = []
        self.microtask_queue: deque[Task] = deque()
        self.macrotask_queue: deque[Task] = deque()
        self.render_requested: bool = False

    def schedule(self, name: str, task_type: TaskType, action: Callable[[], None]) -> None:
        task = Task(name, task_type, action)
        if task_type == TaskType.MICRO:
            self.microtask_queue.append(task)
            print(f"{CLR_GRAY}[V8 Engine]{CLR_RESET} Enqueued Microtask: {CLR_CYAN}{name}{CLR_RESET}")
        else:
            self.macrotask_queue.append(task)
            print(f"{CLR_GRAY}[V8 Engine]{CLR_RESET} Enqueued Macrotask: {CLR_YELLOW}{name}{CLR_RESET}")

    def execute_script(self, script_name: str, script_fn: Callable[['EventLoop'], None]) -> None:
        print(f"\n{CLR_BOLD}{CLR_BLUE}=== Executing Initial Script (Main Thread): {script_name} ==={CLR_RESET}")
        self.call_stack.append(script_name)
        script_fn(self)
        self.call_stack.pop()

    def run_tick(self) -> None:
        print(f"\n{CLR_BOLD}{CLR_MAGENTA}--- Processing Event Loop Tick ---{CLR_RESET}")
        
        # 1. Drain ALL microtasks
        while self.microtask_queue:
            task = self.microtask_queue.popleft()
            print(f"{CLR_CYAN}  -> Executing Microtask:{CLR_RESET} {task.name}")
            task.action()

        # 2. Check if rendering pipeline update is needed
        if self.render_requested:
            print(f"{CLR_GREEN}  -> [Render Opportunity Hook Triggered]{CLR_RESET}")
            self.render_requested = False

        # 3. Execute ONE macrotask
        if self.macrotask_queue:
            task = self.macrotask_queue.popleft()
            print(f"{CLR_YELLOW}  -> Executing Macrotask:{CLR_RESET} {task.name}")
            task.action()

            # Drain any microtasks generated by this macrotask
            while self.microtask_queue:
                mtask = self.microtask_queue.popleft()
                print(f"{CLR_CYAN}    -> Sub-Microtask:{CLR_RESET} {mtask.name}")
                mtask.action()

# ============================================================================
# MODULE 2: HTTP/2 MULTIPLEXED NETWORK LOADER SIMULATION
# ============================================================================

@dataclass
class NetworkFrame:
    stream_id: int
    payload_type: str
    chunk_id: int
    total_chunks: int
    data: str

class HTTP2Multiplexer:
    """Simulates multiplexed binary framing over a single TCP connection."""
    def __init__(self):
        self.frames: deque[NetworkFrame] = deque()
        self.reassembled_streams: Dict[int, List[str]] = {}

    def push_frame(self, stream_id: int, payload_type: str, chunk_id: int, total_chunks: int, data: str):
        self.frames.append(NetworkFrame(stream_id, payload_type, chunk_id, total_chunks, data))

    def process_network_stream(self) -> Dict[str, str]:
        print(f"\n{CLR_BOLD}{CLR_BLUE}=== HTTP/2 Multiplexed Network Engine ==={CLR_RESET}")
        resources: Dict[str, str] = {}
        type_mapping: Dict[int, str] = {}

        while self.frames:
            frame = self.frames.popleft()
            type_mapping[frame.stream_id] = frame.payload_type
            if frame.stream_id not in self.reassembled_streams:
                self.reassembled_streams[frame.stream_id] = ["" for _ in range(frame.total_chunks)]
            
            self.reassembled_streams[frame.stream_id][frame.chunk_id] = frame.data
            print(f"{CLR_GRAY}[TCP/IP]{CLR_RESET} Frame received: Stream {frame.stream_id} "
                  f"({frame.payload_type}) [{frame.chunk_id + 1}/{frame.total_chunks}]")

        for s_id, chunks in self.reassembled_streams.items():
            r_type = type_mapping[s_id]
            resources[r_type] = "".join(chunks)
            print(f"{CLR_GREEN}* Resource fully reassembled:{CLR_RESET} {r_type} ({len(resources[r_type])} bytes)")
        
        return resources

# ============================================================================
# MODULE 3: RENDERING ENGINE PIPELINE (DOM, CSSOM, LAYOUT & PAINT)
# ============================================================================

@dataclass
class DOMNode:
    tag: str
    attributes: Dict[str, str] = field(default_factory=dict)
    children: List['DOMNode'] = field(default_factory=list)
    computed_styles: Dict[str, Any] = field(default_factory=dict)

@dataclass
class Rect:
    x: float
    y: float
    width: float
    height: float

@dataclass
class LayoutBox:
    node: DOMNode
    box_rect: Rect = field(default_factory=lambda: Rect(0, 0, 0, 0))
    children: List['LayoutBox'] = field(default_factory=list)

class RenderingEngine:
    """Simulates Blink/WebKit core: DOM Parser, CSS Cascade, Layout Tree & Rasterizer."""

    def parse_mock_dom(self, html: str) -> DOMNode:
        """Tokenize mock nested HTML: <tag attr='val'>...</tag>."""
        print(f"\n{CLR_BOLD}{CLR_BLUE}=== Pipeline Stage 1: HTML Parsing & DOM Construction ==={CLR_RESET}")
        root = DOMNode(tag="html")
        body = DOMNode(tag="body")
        header = DOMNode(tag="header", attributes={"id": "hero"})
        content = DOMNode(tag="div", attributes={"class": "card"})
        button = DOMNode(tag="button", attributes={"id": "cta"})

        content.children.append(button)
        body.children.extend([header, content])
        root.children.append(body)

        def print_dom(node: DOMNode, indent: int = 0):
            attrs = " ".join([f'{k}="{v}"' for k, v in node.attributes.items()])
            attr_str = f" {attrs}" if attrs else ""
            print(f"{'  ' * indent}{CLR_YELLOW}<{node.tag}{attr_str}>{CLR_RESET}")
            for child in node.children:
                print_dom(child, indent + 1)

        print_dom(root)
        return root

    def apply_cssom_cascade(self, root: DOMNode, css_rules: Dict[str, Dict[str, Any]]) -> None:
        """Computes matching styles per node using specificity cascade emulation."""
        print(f"\n{CLR_BOLD}{CLR_BLUE}=== Pipeline Stage 2: CSSOM Match & Style Computation ==={CLR_RESET}")
        
        def match_and_compute(node: DOMNode):
            # Base default browser styles
            node.computed_styles = {"display": "block", "width": 800.0, "height": 40.0, "color": "#000"}

            # Selector rule matching
            if node.tag in css_rules:
                node.computed_styles.update(css_rules[node.tag])
            if "id" in node.attributes and f"#{node.attributes['id']}" in css_rules:
                node.computed_styles.update(css_rules[f"#{node.attributes['id']}"])
            if "class" in node.attributes and f".{node.attributes['class']}" in css_rules:
                node.computed_styles.update(css_rules[f".{node.attributes['class']}"])

            print(f"Computed Style [{CLR_CYAN}{node.tag}{CLR_RESET}]: "
                  f"display={node.computed_styles.get('display')}, "
                  f"width={node.computed_styles.get('width')}, "
                  f"height={node.computed_styles.get('height')}")

            for child in node.children:
                match_and_compute(child)

        match_and_compute(root)

    def build_layout_tree(self, node: DOMNode, cursor_y: float = 0.0) -> LayoutBox:
        """Reflow/Layout: Calculates explicit geometric coordinates (x, y, w, h)."""
        box = LayoutBox(node=node)
        width = float(node.computed_styles.get("width", 800.0))
        height = float(node.computed_styles.get("height", 40.0))
        
        box.box_rect = Rect(x=0.0, y=cursor_y, width=width, height=height)
        current_y = cursor_y

        for child in node.children:
            child_box = self.build_layout_tree(child, current_y)
            box.children.append(child_box)
            current_y += child_box.box_rect.height  # standard normal flow block accumulation

        return box

    def paint(self, layout_root: LayoutBox) -> List[str]:
        """Generates Display List for the Skia rasterization layer."""
        display_list = []

        def traverse_paint(lbox: LayoutBox):
            r = lbox.box_rect
            tag = lbox.node.tag
            color = lbox.node.computed_styles.get("color", "#000000")
            display_list.append(f"DRAW_RECT x={r.x:.1f}, y={r.y:.1f}, w={r.width:.1f}, h={r.height:.1f} tag=<{tag}>")
            display_list.append(f"SET_BRUSH color={color}")
            for child in lbox.children:
                traverse_paint(child)

        traverse_paint(layout_root)
        return display_list

# ============================================================================
# MAIN ORCHESTRATION PIPELINE
# ============================================================================

def main():
    print(f"{CLR_BOLD}{CLR_GREEN}======================================================================{CLR_RESET}")
    print(f"{CLR_BOLD}{CLR_GREEN}  DEEP DIVE: BROWSER RUNTIME, PROTOCOLS & RENDERING PIPELINES LAB     {CLR_RESET}")
    print(f"{CLR_BOLD}{CLR_GREEN}======================================================================{CLR_RESET}")

    # 1. NETWORK PHASE: Multiplexed Stream Extraction
    net = HTTP2Multiplexer()
    # Stream 1: HTML Document chunks
    net.push_frame(1, "HTML", 0, 2, "<html><body><header id='hero'></header>")
    net.push_frame(1, "HTML", 1, 2, "<div class='card'><button id='cta'>Click</button></div></body></html>")
    # Stream 2: CSS Stylesheet chunks interleaved
    net.push_frame(2, "CSS", 0, 2, "body { width: 1024; } header { height: 120; } ")
    net.push_frame(2, "CSS", 1, 2, ".card { height: 300; width: 600; } #cta { height: 45; width: 150; }")
    
    resources = net.process_network_stream()

    # 2. RENDERING PIPELINE PHASE
    renderer = RenderingEngine()
    dom_root = renderer.parse_mock_dom(resources["HTML"])

    css_rules = {
        "body": {"width": 1024.0, "height": 800.0, "color": "#111111"},
        "#hero": {"width": 1024.0, "height": 120.0, "color": "#0055ff"},
        ".card": {"width": 600.0, "height": 300.0, "color": "#ffffff"},
        "#cta": {"width": 150.0, "height": 45.0, "color": "#00ff66"},
    }
    renderer.apply_cssom_cascade(dom_root, css_rules)

    print(f"\n{CLR_BOLD}{CLR_BLUE}=== Pipeline Stage 3: Layout Tree Geometry (Reflow) ==={CLR_RESET}")
    layout_root = renderer.build_layout_tree(dom_root)

    def print_layout(box: LayoutBox, level: int = 0):
        r = box.box_rect
        print(f"{'  ' * level}Box [{CLR_CYAN}{box.node.tag}{CLR_RESET}] -> "
              f"X: {r.x:5.1f} | Y: {r.y:5.1f} | W: {r.width:6.1f} | H: {r.height:5.1f}")
        for c in box.children:
            print_layout(c, level + 1)

    print_layout(layout_root)

    print(f"\n{CLR_BOLD}{CLR_BLUE}=== Pipeline Stage 4: Paint & Display List Generation ==={CLR_RESET}")
    display_list = renderer.paint(layout_root)
    for cmd in display_list:
        print(f"{CLR_GRAY}[RASTER CMD]{CLR_RESET} {cmd}")

    # 3. RUNTIME / EVENT LOOP EXECUTION PHASE
    loop = EventLoop()

    def user_script(ev: EventLoop):
        print("  [JS Stack] Line 1: console.log('Sync start')")
        
        # Scheduling setTimeout (Macrotask)
        ev.schedule("setTimeout(..., 0)", TaskType.MACRO, 
                    lambda: print("  [Task Body] Executing Timer Handler"))
        
        # Scheduling Promise.then (Microtask)
        ev.schedule("Promise.resolve().then(Callback1)", TaskType.MICRO,
                    lambda: print("  [Microtask Body] Promise 1 Resolved"))

        # Nested Microtask inside script
        ev.schedule("Promise.resolve().then(Callback2)", TaskType.MICRO,
                    lambda: ev.schedule("queueMicrotask(Chained)", TaskType.MICRO, 
                                        lambda: print("  [Microtask Body] Chained microtask handled!")))
        
        # Request Reflow / Invalidation
        ev.render_requested = True
        print("  [JS Stack] Line 4: Mutate DOM (Triggering Layout Request)")
        print("  [JS Stack] Line 5: console.log('Sync end')")

    loop.execute_script("bundle.app.js", user_script)

    # Simulate browser cycles (Ticks)
    loop.run_tick()
    loop.run_tick()

    print(f"\n{CLR_BOLD}{CLR_GREEN}Pipeline Execution Summary:{CLR_RESET}")
    print(f" - Parsed DOM nodes: {CLR_BOLD}5{CLR_RESET}")
    print(f" - CSS Cascade rules applied: {CLR_BOLD}{len(css_rules)}{CLR_RESET}")
    print(f" - Display list commands generated: {CLR_BOLD}{len(display_list)}{CLR_RESET}")
    print(f" - State: Main thread execution completed without unhandled rejections.\n")

if __name__ == "__main__":
    main()