#!/usr/bin/env python3
"""
Lab: R Package Development, Reproducibility, & Testing Engine
Simulates an automated R package build verification system, including:
- R CMD check pipeline (DESCRIPTION, NAMESPACE, and documentation parity)
- Roxygen2 docstring parsing and export consistency checks
- 'renv' deterministic lockfile hashing for environment reproducibility
- 'testthat' behavioral test runner simulation with assertions
"""

import sys
import re
import time
import hashlib
import json
from typing import List, Dict, Tuple, Any

# --- Terminal ANSI Color Constants ---
CLR_RESET  = "\033[0m"
CLR_BOLD   = "\033[1m"
CLR_GREEN  = "\033[32m"
CLR_RED    = "\033[31m"
CLR_YELLOW = "\033[33m"
CLR_BLUE   = "\033[34m"
CLR_CYAN   = "\033[36m"
CLR_MAG    = "\033[35m"

# --- In-Memory Simulated R Package Assets ---
SIMULATED_DESCRIPTION = """Package: fastMetricsR
Type: Package
Title: Robust Numerical Summaries and Variance Estimators
Version: 1.2.0
Authors@R: person("Dev", "Lead", email = "lead@system.org", role = c("aut", "cre"))
Description: High-performance statistical operations with reproducible seeds.
License: MIT + file LICENSE
Encoding: UTF-8
RoxygenNote: 7.2.3
Imports: stats, utils
Suggests: testthat (>= 3.0.0)
"""

SIMULATED_NAMESPACE = """# Generated by roxygen2: do not edit by hand
export(robust_mean)
export(trimmed_variance)
importFrom(stats, median)
importFrom(stats, var)
"""

SIMULATED_R_CODE = """#' Compute Robust Sample Mean
#'
#' Evaluates the arithmetic mean with optional removal of missing values.
#' @param x Numeric vector of observations.
#' @param na_rm Logical flag indicating whether NA values should be stripped.
#' @return Numeric scalar representing the mean.
#' @export
robust_mean <- function(x, na_rm = FALSE) {
    if (na_rm) {
        x <- x[!is.na(x)]
    }
    if (length(x) == 0) return(NaN)
    return(sum(x) / length(x))
}

#' Compute Trimmed Variance
#'
#' Computes variance after trimming alpha outliers from tails.
#' @param x Numeric vector.
#' @param trim Fraction (0 to 0.5) of observations to trim.
#' @return Numeric scalar representing sample variance.
#' @export
trimmed_variance <- function(x, trim = 0.1) {
    if (trim < 0 || trim >= 0.5) stop("trim must be in [0, 0.5)")
    n <- length(x)
    k <- floor(n * trim)
    x_sorted <- sort(x)
    x_cut <- x_sorted[(k + 1):(n - k)]
    return(var(x_cut))
}
"""

SIMULATED_RENV_LOCK = {
    "R": {"Version": "4.3.2", "Repositories": [{"Name": "CRAN", "URL": "https://cloud.r-project.org"}]},
    "Packages": {
        "stats": {"Package": "stats", "Version": "4.3.2", "Source": "Built-in", "Hash": "c0a801fa"},
        "testthat": {"Package": "testthat", "Version": "3.2.0", "Source": "CRAN", "Hash": "9bfa774e"}
    },
    "SourceHash": ""  # Calculated dynamically
}

# --- Module 1: Reproducibility & Cryptographic Verification ---
def calculate_source_hash(r_code: str) -> str:
    """Computes SHA-256 fingerprint of R source to enforce reproducibility (like renv/packrat)."""
    sha256 = hashlib.sha256()
    sha256.update(r_code.encode("utf-8"))
    return sha256.hexdigest()

def verify_reproducibility_lockfile(source_code: str, lockfile: Dict[str, Any]) -> Tuple[bool, str]:
    """Validates if current source matches recorded lockfile checksum."""
    current_hash = calculate_source_hash(source_code)
    lockfile["SourceHash"] = current_hash  # Initialize baseline lock
    # Verification round-trip simulation
    recorded_hash = lockfile.get("SourceHash")
    is_valid = (current_hash == recorded_hash)
    return is_valid, current_hash

# --- Module 2: Roxygen2 & NAMESPACE Linter ---
class RoxygenParser:
    """Parses Roxygen2 tags and verifies 1:1 documentation parity with NAMESPACE exports."""

    @staticmethod
    def parse_exports_and_params(code: str) -> Dict[str, Dict[str, Any]]:
        functions = {}
        pattern = re.compile(
            r"((?:#'[^\n]*\n)+)\s*([a-zA-Z0-9_\.]+)\s*<-\s*function\s*\((.*?)\)",
            re.MULTILINE
        )
        for match in pattern.finditer(code):
            docblock, fn_name, params_raw = match.groups()
            is_exported = "#' @export" in docblock
            params = [p.strip().split("=")[0].strip() for p in params_raw.split(",") if p.strip()]
            
            # Extract @param declarations
            doc_params = re.findall(r"#'\s+@param\s+([a-zA-Z0-9_\.]+)", docblock)
            doc_return = "#' @return" in docblock
            
            functions[fn_name] = {
                "exported": is_exported,
                "code_params": params,
                "doc_params": doc_params,
                "has_return": doc_return
            }
        return functions

# --- Module 3: Mock 'testthat' Unit Test Runner ---
class MockTestThatRunner:
    """Simulates R 'testthat' framework assertions and reporting."""

    def __init__(self):
        self.total_tests = 0
        self.passed_tests = 0
        self.failed_tests = 0
        self.failures = []

    def expect_equal(self, actual: float, expected: float, label: str, tolerance: float = 1e-6):
        self.total_tests += 1
        if abs(actual - expected) <= tolerance:
            self.passed_tests += 1
            print(f"  {CLR_GREEN}[PASS]{CLR_RESET} expect_equal: {label}")
        else:
            self.failed_tests += 1
            err = f"Actual {actual} != Expected {expected}"
            self.failures.append((label, err))
            print(f"  {CLR_RED}[FAIL]{CLR_RESET} expect_equal: {label} -> {err}")

    def expect_error(self, callable_obj, label: str):
        self.total_tests += 1
        try:
            callable_obj()
            self.failed_tests += 1
            err = "Did not throw expected error condition"
            self.failures.append((label, err))
            print(f"  {CLR_RED}[FAIL]{CLR_RESET} expect_error: {label} -> {err}")
        except Exception:
            self.passed_tests += 1
            print(f"  {CLR_GREEN}[PASS]{CLR_RESET} expect_error: {label}")

# Simulated Python implementations of the R functions to run assertions against
def r_robust_mean(x: List[float], na_rm: bool = False) -> float:
    filtered = [v for v in x if v is not None and not (isinstance(v, float) and v != v)]
    if not na_rm and len(filtered) != len(x):
        return float('nan')
    if not filtered:
        return float('nan')
    return sum(filtered) / len(filtered)

def r_trimmed_variance(x: List[float], trim: float = 0.1) -> float:
    if trim < 0 or trim >= 0.5:
        raise ValueError("trim must be in [0, 0.5)")
    n = len(x)
    k = int(n * trim)
    sorted_x = sorted(x)
    cut = sorted_x[k:n - k]
    if len(cut) < 2:
        return 0.0
    mean_val = sum(cut) / len(cut)
    return sum((v - mean_val) ** 2 for v in cut) / (len(cut) - 1)

# --- Module 4: R CMD check Pipeline Orchestrator ---
class RCMDCheckPipeline:
    def __init__(self):
        self.errors = []
        self.warnings = []
        self.notes = []

    def check_description(self, desc_text: str):
        print(f"{CLR_BLUE}* checking DESCRIPTION meta-information ...{CLR_RESET}")
        time.sleep(0.1)
        required_fields = ["Package", "Version", "License", "Description", "Title"]
        for field in required_fields:
            if not re.search(rf"^{field}:", desc_text, re.MULTILINE):
                self.errors.append(f"Missing mandatory field '{field}' in DESCRIPTION")
        
        # Check SemVer
        ver_match = re.search(r"^Version:\s*([^\n]+)", desc_text, re.MULTILINE)
        if ver_match:
            ver = ver_match.group(1).strip()
            if not re.match(r"^\d+\.\d+\.\d+$", ver):
                self.warnings.append(f"Non-standard package version format: {ver}")
        print(f"  OK: DESCRIPTION adheres to CRAN specification.")

    def check_namespace_and_docs(self, r_code: str, namespace_text: str):
        print(f"{CLR_BLUE}* checking NAMESPACE and documentation parity (roxygen2) ...{CLR_RESET}")
        time.sleep(0.1)
        # Parse exported functions from NAMESPACE
        exported_ns = set(re.findall(r"export\(([a-zA-Z0-9_\.]+)\)", namespace_text))
        
        # Parse Roxygen
        fn_meta = RoxygenParser.parse_exports_and_params(r_code)
        
        for fn_name, meta in fn_meta.items():
            if meta["exported"] and fn_name not in exported_ns:
                self.warnings.append(f"Function '{fn_name}' has @export but is missing in NAMESPACE")
            if not meta["has_return"]:
                self.notes.append(f"Undocumented @return for function '{fn_name}'")
            
            # Check parameter parity
            undoc_params = set(meta["code_params"]) - set(meta["doc_params"])
            if undoc_params:
                self.warnings.append(f"Undocumented parameter(s) {undoc_params} in function '{fn_name}'")

        print(f"  OK: {len(exported_ns)} exports parsed, docstrings verified.")

    def run_tests(self):
        print(f"{CLR_BLUE}* running automated testthat test suites ...{CLR_RESET}")
        runner = MockTestThatRunner()
        
        # Test Suite 1: robust_mean
        print(f"{CLR_CYAN}  Context: robust_mean computations{CLR_RESET}")
        test_vec = [10.0, 20.0, 30.0, 40.0, 50.0]
        runner.expect_equal(r_robust_mean(test_vec), 30.0, "Basic mean calculation")
        
        test_vec_na = [10.0, None, 30.0]
        runner.expect_equal(r_robust_mean(test_vec_na, na_rm=True), 20.0, "Mean with NA removal")
        
        # Test Suite 2: trimmed_variance
        print(f"{CLR_CYAN}  Context: trimmed_variance computations{CLR_RESET}")
        test_data = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
        # Trim 0.1 -> 1 element from each tail -> [2.0 .. 9.0]
        runner.expect_equal(r_trimmed_variance(test_data, trim=0.1), 6.0, "10% Trimmed variance on [1..10]")
        runner.expect_error(lambda: r_trimmed_variance(test_data, trim=0.6), "Error on invalid trim argument")

        if runner.failed_tests > 0:
            self.errors.append(f"testthat encountered {runner.failed_tests} failed assertions")

    def run_reproducibility_audit(self, r_code: str):
        print(f"{CLR_BLUE}* checking renv environment reproducibility lockfile ...{CLR_RESET}")
        time.sleep(0.1)
        valid, chksum = verify_reproducibility_lockfile(r_code, SIMULATED_RENV_LOCK)
        if valid:
            print(f"  {CLR_GREEN}SHA-256 Digest:{CLR_RESET} {chksum[:24]}... (REPRODUCIBLE BUILD CONFIRMED)")
        else:
            self.errors.append("Reproducibility check failed: Source digest mismatch against renv.lock")

    def print_summary(self):
        print("\n" + "=" * 65)
        print(f"{CLR_BOLD}R CMD check RESULT SUMMARY:{CLR_RESET}")
        print("=" * 65)
        
        err_clr = CLR_RED if self.errors else CLR_GREEN
        warn_clr = CLR_YELLOW if self.warnings else CLR_GREEN
        note_clr = CLR_CYAN if self.notes else CLR_GREEN

        print(f"Status: {err_clr}{len(self.errors)} ERROR(s){CLR_RESET}, "
              f"{warn_clr}{len(self.warnings)} WARNING(s){CLR_RESET}, "
              f"{note_clr}{len(self.notes)} NOTE(s){CLR_RESET}")

        for err in self.errors:
            print(f"  {CLR_RED}ERROR:{CLR_RESET} {err}")
        for warn in self.warnings:
            print(f"  {CLR_YELLOW}WARNING:{CLR_RESET} {warn}")
        for note in self.notes:
            print(f"  {CLR_CYAN}NOTE:{CLR_RESET} {note}")

        if not self.errors and not self.warnings:
            print(f"\n{CLR_GREEN}{CLR_BOLD}SUCCESS:{CLR_RESET} Package 'fastMetricsR' passes CRAN criteria.")
        else:
            print(f"\n{CLR_RED}{CLR_BOLD}FAIL:{CLR_RESET} Issues must be resolved before submission.")


def main():
    print(f"{CLR_BOLD}{CLR_MAG}=== Deep Dive: R Package Infrastructure, Testing & Reproducibility ==={CLR_RESET}\n")
    pipeline = RCMDCheckPipeline()
    
    # 1. Inspect metadata
    pipeline.check_description(SIMULATED_DESCRIPTION)
    
    # 2. Inspect documentation & NAMESPACE sync
    pipeline.check_namespace_and_docs(SIMULATED_R_CODE, SIMULATED_NAMESPACE)
    
    # 3. Cryptographic reproducibility check
    pipeline.run_reproducibility_audit(SIMULATED_R_CODE)
    
    # 4. Unit testing via testthat simulation
    pipeline.run_tests()
    
    # 5. Output check summary
    pipeline.print_summary()


if __name__ == "__main__":
    main()