#!/usr/bin/env python3
"""
Lab Hands-on: Advanced Frontend Reconciliation Engine & Batch Update Pipeline
Topic: Frontend Architecture (03-Frontend-and-Mobile) - Chapter 07, Module 02 Deep Dive

Simulates the core internal mechanics of modern Frontend Frameworks (Virtual DOM diffing,
patch compilation, batched state scheduling, and simulated DOM tree reconciliation).
"""

import sys
import time
import json
from typing import Dict, List, Any, Optional, Union

# ANSI terminal formatting
CLR_RESET = "\033[0m"
CLR_BOLD = "\033[1m"
CLR_RED = "\033[31m"
CLR_GREEN = "\033[32m"
CLR_YELLOW = "\033[33m"
CLR_BLUE = "\033[34m"
CLR_MAGENTA = "\033[35m"
CLR_CYAN = "\033[36m"


class VNode:
    """Represents a lightweight Virtual DOM Node."""
    def __init__(
        self,
        tag: str,
        props: Optional[Dict[str, Any]] = None,
        children: Optional[List[Union['VNode', str]]] = None,
        key: Optional[str] = None
    ):
        self.tag = tag
        self.props = props or {}
        self.children = children or []
        self.key = key or self.props.get("key")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "tag": self.tag,
            "key": self.key,
            "props": self.props,
            "children": [
                c.to_dict() if isinstance(c, VNode) else c for c in self.children
            ]
        }


def h(tag: str, props: Optional[Dict[str, Any]] = None, children: Optional[List[Union[VNode, str]]] = None, key: Optional[str] = None) -> VNode:
    """Hyperscript factory function to construct VNodes."""
    return VNode(tag=tag, props=props, children=children, key=key)


class PatchType:
    REPLACE = "REPLACE"
    UPDATE_PROPS = "UPDATE_PROPS"
    TEXT_CHANGE = "TEXT_CHANGE"
    CHILDREN_REORDER = "CHILDREN_REORDER"


class Patch:
    """Encapsulates a granular DOM operation generated by the diffing engine."""
    def __init__(self, p_type: str, path: str, payload: Any):
        self.type = p_type
        self.path = path  # Tree path locator e.g. "0.1" (root -> child 0 -> child 1)
        self.payload = payload

    def __repr__(self):
        return f"Patch(type={self.type}, path='{self.path}', payload={self.payload})"


class ReconciliationEngine:
    """
    Core heuristic O(N) Diffing Algorithm modeling React/Vue reconciliation:
    1. Elements of different tags produce entirely new subtrees.
    2. Keys are utilized to match elements across render cycles for optimal list moves.
    3. Granular prop diffing prevents full element attribute destruction.
    """

    def diff(self, old_node: Union[VNode, str, None], new_node: Union[VNode, str, None], path: str = "root") -> List[Patch]:
        patches: List[Patch] = []

        # 1. Edge Case: Node removed or completely replaced
        if old_node is None and new_node is not None:
            return [Patch(PatchType.REPLACE, path, {"old": None, "new": new_node})]
        if old_node is not None and new_node is None:
            return [Patch(PatchType.REPLACE, path, {"old": old_node, "new": None})]
        if old_node is None and new_node is None:
            return []

        # 2. Text node diffing
        if isinstance(old_node, str) or isinstance(new_node, str):
            if old_node != new_node:
                patches.append(Patch(PatchType.TEXT_CHANGE, path, {"from": old_node, "to": new_node}))
            return patches

        # 3. Type/Tag discrepancy requires full replacement
        if old_node.tag != new_node.tag:
            patches.append(Patch(PatchType.REPLACE, path, {"old": old_node, "new": new_node}))
            return patches

        # 4. Props Diffing
        prop_diff = self._diff_props(old_node.props, new_node.props)
        if prop_diff:
            patches.append(Patch(PatchType.UPDATE_PROPS, path, prop_diff))

        # 5. Children Diffing (Keyed List Strategy)
        patches.extend(self._diff_children(old_node.children, new_node.children, path))

        return patches

    def _diff_props(self, old_props: Dict[str, Any], new_props: Dict[str, Any]) -> Dict[str, Any]:
        delta = {"set": {}, "unset": []}
        for k, v in new_props.items():
            if k not in old_props or old_props[k] != v:
                delta["set"][k] = v
        for k in old_props:
            if k not in new_props:
                delta["unset"].append(k)

        if not delta["set"] and not delta["unset"]:
            return {}
        return delta

    def _diff_children(self, old_children: List[Union[VNode, str]], new_children: List[Union[VNode, str]], parent_path: str) -> List[Patch]:
        patches = []
        old_keyed = {c.key: (i, c) for i, c in enumerate(old_children) if isinstance(c, VNode) and c.key}
        new_keyed = {c.key: (i, c) for i, c in enumerate(new_children) if isinstance(c, VNode) and c.key}

        # If keyed children exist, evaluate keyed reordering/diffing
        if old_keyed and new_keyed:
            moves = []
            for key, (new_idx, new_c) in new_keyed.items():
                if key in old_keyed:
                    old_idx, old_c = old_keyed[key]
                    if old_idx != new_idx:
                        moves.append({"key": key, "from": old_idx, "to": new_idx})
                    # Recursively diff matched child
                    patches.extend(self.diff(old_c, new_c, f"{parent_path}.{key}"))
                else:
                    moves.append({"action": "INSERT", "key": key, "at": new_idx, "node": new_c})

            for key, (old_idx, _) in old_keyed.items():
                if key not in new_keyed:
                    moves.append({"action": "REMOVE", "key": key, "at": old_idx})

            if moves:
                patches.append(Patch(PatchType.CHILDREN_REORDER, parent_path, moves))
        else:
            # Fallback to index-based linear diffing
            max_len = max(len(old_children), len(new_children))
            for i in range(max_len):
                child_path = f"{parent_path}[{i}]"
                o_c = old_children[i] if i < len(old_children) else None
                n_c = new_children[i] if i < len(new_children) else None
                patches.extend(self.diff(o_c, n_c, child_path))

        return patches


class SimulatedRealDOM:
    """Simulates actual browser DOM tree mutations and counts expensive layout/write operations."""
    def __init__(self):
        self.mutation_count = 0

    def apply_patches(self, patches: List[Patch]):
        for patch in patches:
            self.mutation_count += 1
            if patch.type == PatchType.REPLACE:
                print(f"  {CLR_RED}⚡ [Real DOM Write]{CLR_RESET} Replace at `{patch.path}`")
            elif patch.type == PatchType.UPDATE_PROPS:
                print(f"  {CLR_YELLOW}⚡ [Real DOM Attr]{CLR_RESET} Mutate attributes at `{patch.path}` -> {patch.payload}")
            elif patch.type == PatchType.TEXT_CHANGE:
                print(f"  {CLR_CYAN}⚡ [Real DOM Text]{CLR_RESET} Text changed at `{patch.path}`: '{patch.payload['from']}' -> '{patch.payload['to']}'")
            elif patch.type == PatchType.CHILDREN_REORDER:
                print(f"  {CLR_MAGENTA}⚡ [Real DOM Layout]{CLR_RESET} Reorder children at `{patch.path}`: {len(patch.payload)} operations")


class ReactiveComponent:
    """Reactive Component implementing micro-batch updates and dirty rendering."""
    def __init__(self, name: str):
        self.name = name
        self.state: Dict[str, Any] = {}
        self._pending_state: Dict[str, Any] = {}
        self._is_batching = False
        self._current_vdom: Optional[VNode] = None
        self.engine = ReconciliationEngine()
        self.real_dom = SimulatedRealDOM()

    def set_state(self, updates: Dict[str, Any]):
        """Schedules updates within a batched lifecycle."""
        self._pending_state.update(updates)
        if not self._is_batching:
            self._is_batching = True
            self._schedule_render()

    def _schedule_render(self):
        # Simulate microtask dispatch
        self.state.update(self._pending_state)
        self._pending_state.clear()
        self._is_batching = False
        self._render_cycle()

    def render(self) -> VNode:
        raise NotImplementedError

    def _render_cycle(self):
        start_time = time.perf_counter_ns()
        new_vdom = self.render()
        diff_time = time.perf_counter_ns() - start_time

        print(f"\n{CLR_BOLD}[Lifecycle Trigger]{CLR_RESET} Re-rendering Component <{self.name} />")
        patches = self.engine.diff(self._current_vdom, new_vdom)
        
        print(f"  ↳ Diffing Phase: Found {CLR_BOLD}{len(patches)}{CLR_RESET} patch instructions in {diff_time / 1000:.2f} µs")
        
        self.real_dom.apply_patches(patches)
        self._current_vdom = new_vdom


class TaskDashboard(ReactiveComponent):
    """Concrete Frontend Component implementation rendering a dynamic task tracker."""
    def __init__(self):
        super().__init__("TaskDashboard")
        self.state = {
            "filter": "ALL",
            "theme": "dark",
            "tasks": [
                {"id": "t1", "title": "Implement Diff Engine", "done": True},
                {"id": "t2", "title": "Batch State Pipelines", "done": False},
                {"id": "t3", "title": "Keyed Child Reordering", "done": False}
            ]
        }
        self._render_cycle()

    def render(self) -> VNode:
        visible_tasks = self.state["tasks"]
        if self.state["filter"] == "PENDING":
            visible_tasks = [t for t in visible_tasks if not t["done"]]

        task_elements = [
            h(
                "li",
                props={"class": "task-item", "data-done": t["done"]},
                children=[
                    h("span", props={"class": "task-title"}, children=[t["title"]]),
                    h("span", props={"class": "badge"}, children=["[DONE]" if t["done"] else "[PENDING]"])
                ],
                key=t["id"]
            )
            for t in visible_tasks
        ]

        return h("div", props={"id": "app-container", "theme": self.state["theme"]}, children=[
            h("header", children=[
                h("h1", children=["Task Runtime Dashboard"]),
                h("span", props={"class": "status"}, children=[f"Filter: {self.state['filter']}"])
            ]),
            h("ul", props={"class": "task-list"}, children=task_elements),
            h("footer", children=[f"Total tasks rendered: {len(visible_tasks)}"])
        ])


def main():
    print(f"{CLR_BOLD}{CLR_GREEN}======================================================================{CLR_RESET}")
    print(f"{CLR_BOLD}{CLR_GREEN}   SYSTEM SIMULATION: Virtual DOM Diffing & Reconciliation Pipeline   {CLR_RESET}")
    print(f"{CLR_BOLD}{CLR_GREEN}======================================================================{CLR_RESET}")

    # Mount initial component tree
    dashboard = TaskDashboard()

    # Step 1: Attribute Mutation (Theme Change)
    print(f"\n{CLR_BOLD}>>> SCENARIO 1: Prop Mutation Only (Dark -> Light Theme){CLR_RESET}")
    dashboard.set_state({"theme": "light"})

    # Step 2: Keyed List Re-ordering & Content Mutation
    print(f"\n{CLR_BOLD}>>> SCENARIO 2: Task Completion & Reordering (Keyed Diffing){CLR_RESET}")
    mutated_tasks = [
        {"id": "t2", "title": "Batch State Pipelines (Optimized)", "done": True}, # Updated text & state
        {"id": "t1", "title": "Implement Diff Engine", "done": True},             # Swapped index
        {"id": "t3", "title": "Keyed Child Reordering", "done": False},
        {"id": "t4", "title": "Synthetic Event Bubbling", "done": False}         # New node insertion
    ]
    dashboard.set_state({"tasks": mutated_tasks})

    # Step 3: Structural Filtering (Node Removal via list reduction)
    print(f"\n{CLR_BOLD}>>> SCENARIO 3: Conditional Branching & Node Eviction (Filter Active){CLR_RESET}")
    dashboard.set_state({"filter": "PENDING"})

    # Performance Audit Summary
    print(f"\n{CLR_BOLD}{CLR_CYAN}------------------------ RECONCILIATION SUMMARY ------------------------{CLR_RESET}")
    print(f"Total Real DOM Operations Performed: {CLR_BOLD}{dashboard.real_dom.mutation_count}{CLR_RESET}")
    naive_writes = 1 + 2 + 4 + 4  # Initial Mount + Scenarios full redraws
    print(f"Naive Full-Tree Re-renders Prevented: {CLR_BOLD}{naive_writes - dashboard.real_dom.mutation_count}{CLR_RESET} redundant updates avoided")
    print(f"{CLR_GREEN}Reconciliation complete. DOM integrity maintained with optimal patches.{CLR_RESET}\n")


if __name__ == "__main__":
    main()