#!/usr/bin/env python3
"""
Enterprise Scala Testing, Observability & Delivery Pipeline Simulator
BAB 10: Pengujian Enterprise, Observabilitas & Delivery (Scala Ecosystem)

Simulasi komprehensif konsep enterprise Scala:
1. Testing Framework: ScalaTest Spec & ScalaCheck Property-Based Testing (Generator & Shrinking)
2. Observability: OpenTelemetry Distributed Tracing (Trace/Span ID, Context Propagation) & Prometheus Metrics
3. Enterprise Delivery: sbt-native-packager, Container Build & Canary Deployment Pipeline
"""

import sys
import time
import uuid
import random
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Callable, Any

# ANSI Terminal Colors
class Color:
    RESET = "\033[0m"
    BOLD = "\033[1m"
    DIM = "\033[2m"
    UNDERLINE = "\033[4m"
    
    RED = "\033[31m"
    GREEN = "\033[32m"
    YELLOW = "\033[33m"
    BLUE = "\033[34m"
    MAGENTA = "\033[35m"
    CYAN = "\033[36m"
    WHITE = "\033[37m"
    
    BG_BLUE = "\033[44m"
    BG_GREEN = "\033[42m"
    BG_RED = "\033[41m"
    BG_DARK = "\033[40m"

def print_header(title: str):
    print(f"\n{Color.BOLD}{Color.CYAN}{'=' * 75}{Color.RESET}")
    print(f"{Color.BOLD}{Color.WHITE}  SCALA ENTERPRISE PLATFORM: {title.upper()}{Color.RESET}")
    print(f"{Color.BOLD}{Color.CYAN}{'=' * 75}{Color.RESET}")

def print_badge(label: str, text: str, color: str = Color.GREEN):
    print(f" {Color.BOLD}{color}[{label}]{Color.RESET} {text}")

# ==============================================================================
# 1. SCALA TESTING ENGINE (ScalaTest & ScalaCheck Simulation)
# ==============================================================================

@dataclass
class TestResult:
    spec_name: str
    assertion: str
    passed: bool
    latency_ms: float
    error_msg: Optional[str] = None

class ScalaTestEngine:
    def __init__(self):
        self.results: List[TestResult] = []

    def flat_spec(self, behavior: str, test_fn: Callable[[], bool]):
        t0 = time.perf_counter()
        passed = False
        err = None
        try:
            passed = test_fn()
        except Exception as e:
            err = str(e)
            passed = False
        elapsed = (time.perf_counter() - t0) * 1000.0
        result = TestResult(spec_name=behavior, assertion="should conform to spec", passed=passed, latency_ms=elapsed, error_msg=err)
        self.results.append(result)
        return result

    def scalacheck_property(self, prop_name: str, sample_size: int, property_fn: Callable[[int], bool]):
        t0 = time.perf_counter()
        passed = True
        failing_seed = None
        for i in range(sample_size):
            sample = random.randint(-1000, 1000)
            if not property_fn(sample):
                passed = False
                failing_seed = sample
                break
        elapsed = (time.perf_counter() - t0) * 1000.0
        
        err = None
        if not passed:
            # Simulate shrinking to minimal falsified counter-example
            err = f"Falsified after sample count! Counterexample: {failing_seed} (Shrunk -> 0)"
        
        result = TestResult(
            spec_name=f"Property: {prop_name} ({sample_size} runs)",
            assertion="forAll samples generated by Gen[Int]",
            passed=passed,
            latency_ms=elapsed,
            error_msg=err
        )
        self.results.append(result)
        return result

# ==============================================================================
# 2. OBSERVABILITY ENGINE (OpenTelemetry & Prometheus Simulation)
# ==============================================================================

@dataclass
class Span:
    trace_id: str
    span_id: str
    parent_span_id: Optional[str]
    name: str
    duration_ms: float
    attributes: Dict[str, Any] = field(default_factory=dict)
    status: str = "OK"

class OpenTelemetryTracer:
    def __init__(self, service_name: str):
        self.service_name = service_name
        self.spans: List[Span] = []
        self.metrics_counters: Dict[str, int] = {}
        self.metrics_latency: Dict[str, List[float]] = {}

    def new_trace_id(self) -> str:
        return uuid.uuid4().hex[:16]

    def new_span_id(self) -> str:
        return uuid.uuid4().hex[:8]

    def record_metric(self, name: str, value: float):
        if name not in self.metrics_latency:
            self.metrics_latency[name] = []
            self.metrics_counters[name] = 0
        self.metrics_counters[name] += 1
        self.metrics_latency[name].append(value)

    def create_span(self, trace_id: str, name: str, parent_id: Optional[str] = None, duration_ms: float = 15.0, attrs: Dict[str, Any] = None) -> Span:
        span = Span(
            trace_id=trace_id,
            span_id=self.new_span_id(),
            parent_span_id=parent_id,
            name=name,
            duration_ms=duration_ms,
            attributes=attrs or {"service.name": self.service_name}
        )
        self.spans.append(span)
        self.record_metric(f"{self.service_name}.span.duration", duration_ms)
        return span

# ==============================================================================
# 3. DELIVERY & CI/CD DEPLOYMENT PIPELINE
# ==============================================================================

class DeliveryPipeline:
    def __init__(self, artifact_name: str, version: str):
        self.artifact_name = artifact_name
        self.version = version

    def run_stage(self, stage_name: str, delay: float = 0.25) -> bool:
        sys.stdout.write(f"  {Color.YELLOW}⏳ [{stage_name}] In progress...{Color.RESET}")
        sys.stdout.flush()
        time.sleep(delay)
        sys.stdout.write(f"\r  {Color.GREEN}✔ [{stage_name}] COMPLETED!{Color.RESET}\n")
        return True

    def canary_rollout(self, steps: List[int]):
        print(f"\n  {Color.BOLD}{Color.MAGENTA}>>> Initiating Kubernetes Canary Deployment (Argo Rollouts) <<<{Color.RESET}")
        for percentage in steps:
            bar_len = percentage // 4
            bar = f"{Color.BG_GREEN}{' ' * bar_len}{Color.RESET}{' ' * (25 - bar_len)}"
            print(f"  [{bar}] {Color.BOLD}{percentage}% traffic directed to v{self.version}{Color.RESET} (Canary health: 200 OK)")
            time.sleep(0.2)

# ==============================================================================
# INTERACTIVE CLI DEMO & RUNNER
# ==============================================================================

def run_suite():
    print_header("Scala Enterprise Observability & Delivery Simulator")
    print(f"{Color.DIM}Target Stack: Scala 3.3 LTS | ZIO / Cats Effect | ScalaTest | OpenTelemetry | sbt-docker{Color.RESET}\n")

    # --- Phase 1: ScalaTest & Property Testing ---
    print(f"{Color.BOLD}{Color.WHITE}Step 1: Menjalankan Enterprise Test Suite (ScalaTest + ScalaCheck){Color.RESET}")
    tester = ScalaTestEngine()

    # Unit Tests
    tester.flat_spec("AccountService when deposit should increment balance atomically", lambda: True)
    tester.flat_spec("OrderFulfillmentActor should handle PoisonPill gracefully in cluster", lambda: True)
    tester.flat_spec("JwtTokenValidator should reject expired RSA signatures", lambda: True)
    
    # Property-based tests
    tester.scalacheck_property("Monoid associative law: (a + b) + c == a + (b + c)", 100, lambda x: (x + 42) - 42 == x)
    tester.scalacheck_property("Idempotent idempotentOperation: f(f(x)) == f(x)", 50, lambda x: abs(abs(x)) == abs(x))

    for res in tester.results:
        status_color = Color.GREEN if res.passed else Color.RED
        status_txt = "PASSED" if res.passed else "FAILED"
        print(f"  {Color.BOLD}{status_color}[{status_txt}]{Color.RESET} {res.spec_name} {Color.DIM}({res.latency_ms:.2f} ms){Color.RESET}")
        if res.error_msg:
            print(f"      {Color.RED}↳ {res.error_msg}{Color.RESET}")

    # --- Phase 2: Distributed Tracing & OpenTelemetry ---
    print(f"\n{Color.BOLD}{Color.WHITE}Step 2: Menghasilkan OpenTelemetry Distributed Traces & Metrics{Color.RESET}")
    tracer = OpenTelemetryTracer("order-checkout-service")
    trace_id = tracer.new_trace_id()
    
    root_span = tracer.create_span(trace_id, "HTTP POST /api/v2/orders/checkout", None, 68.4, {"http.status_code": 200, "client.id": "enterprise-corp"})
    db_span = tracer.create_span(trace_id, "PostgreSQL executeQuery (Slick/Doobie)", root_span.span_id, 24.1, {"db.system": "postgresql", "db.name": "orderdb"})
    event_span = tracer.create_span(trace_id, "KafkaProducer publish (fs2-kafka)", root_span.span_id, 12.5, {"messaging.system": "kafka", "topic": "orders.v1"})
    cache_span = tracer.create_span(trace_id, "Redis checkCache (ZIO Redis)", root_span.span_id, 3.2, {"db.redis.hit": True})

    print(f"  {Color.BOLD}{Color.CYAN}Distributed Trace ID:{Color.RESET} {trace_id}")
    for span in tracer.spans:
        indent = "    " if span.parent_span_id else "  "
        print(f"{indent}↳ {Color.MAGENTA}[SPAN: {span.span_id}]{Color.RESET} {span.name} - {Color.YELLOW}{span.duration_ms:.1f}ms{Color.RESET}")
        for k, v in span.attributes.items():
            print(f"{indent}    {Color.DIM}{k} = {v}{Color.RESET}")

    # Prometheus Metric Export
    print(f"\n  {Color.BOLD}{Color.WHITE}Prometheus Metric Registry Preview:{Color.RESET}")
    print_badge("METRIC", "http_requests_total{service=\"order-checkout\", status=\"200\"} 14205 ops", Color.CYAN)
    print_badge("METRIC", "jvm_gc_pause_seconds_sum 0.042 (G1GC concurrent)", Color.CYAN)
    print_badge("METRIC", "zio_fiber_active_count 340 fibers", Color.CYAN)

    # --- Phase 3: Delivery Pipeline ---
    print(f"\n{Color.BOLD}{Color.WHITE}Step 3: Enterprise Packaging & GitOps Deployment Pipeline{Color.RESET}")
    pipeline = DeliveryPipeline("scala-enterprise-platform", "1.10.4-RELEASE")
    pipeline.run_stage("sbt clean compile test")
    pipeline.run_stage("sbt native-packager:stage & Docker build --tag=enterprise/scala-app:1.10.4")
    pipeline.run_stage("Trivy Vulnerability & SBOM Security Scan (Critical: 0, High: 0)")
    pipeline.run_stage("Push Image to Harbor Enterprise Registry (sha256:d8a2bf74...)")
    pipeline.run_stage("GitOps commit updated deployment manifest to repo")

    pipeline.canary_rollout([10, 25, 50, 100])

    print_header("Hasil Observabilitas & Status Pipeline")
    print_badge("STATUS", "Semua komponen pengujian, telemetri, dan delivery berhasil!", Color.GREEN)
    print(f"  {Color.DIM}Lab simulasi telah selesai dieksekusi secara mandiri.{Color.RESET}\n")

if __name__ == "__main__":
    run_suite()
