#!/usr/bin/env python3
"""
R Package Development, Testing & Reproducibility Simulator (BAB 09)
-------------------------------------------------------------------
Simulates key workflows from the R package ecosystem:
  1. devtools::create() & Roxygen2 documentation generation
  2. testthat suite runner (unit tests with expect_equal / expect_error)
  3. R CMD check (DESCRIPTION, NAMESPACE, license, and doc checks)
  4. renv lockfile dependency tracking & snapshot/restore
  5. targets / drake reproducible computational pipeline runner
"""

import sys
import time
import json
import hashlib
from typing import Dict, List, Any

# ANSI Color Codes for terminal styling
RESET = "\033[0m"
BOLD = "\033[1m"
DIM = "\033[2m"
RED = "\033[91m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
BLUE = "\033[94m"
MAGENTA = "\033[95m"
CYAN = "\033[96m"
WHITE = "\033[97m"
BG_BLUE = "\033[44m"
BG_GRAY = "\033[100m"


def header(title: str) -> None:
    print(f"\n{BOLD}{CYAN}=== {title.upper()} ==={RESET}\n")


def status_badge(text: str, success: bool = True) -> str:
    if success:
        return f"{BOLD}{GREEN}[✓ {text}]{RESET}"
    return f"{BOLD}{RED}[✗ {text}]{RESET}"


def step_print(step_num: int, label: str) -> None:
    print(f"{BOLD}{BLUE}── ({step_num}) {label}{RESET}")


class RPackageSimulator:
    def __init__(self, pkg_name: str = "faststats", version: str = "0.1.0"):
        self.pkg_name = pkg_name
        self.version = version
        self.description = {
            "Package": pkg_name,
            "Title": "High-Performance Summary Statistics for Tabular Data",
            "Version": version,
            "Authors@R": 'person("Ada", "Lovelace", email="ada@example.com", role=c("aut", "cre"))',
            "Description": "Provides reproducible, high-throughput calculation of standard deviations and medians.",
            "License": "MIT + file LICENSE",
            "Imports": ["rlang (>= 1.0.0)", "vctrs (>= 0.5.0)"],
            "Suggests": ["testthat (>= 3.0.0)", "knitr", "rmarkdown"],
            "RoxygenNote": "7.3.1",
        }
        self.functions = {
            "calculate_trim_mean": {
                "params": ["x", "trim = 0.1", "na_rm = TRUE"],
                "export": True,
                "doc": "Compute trimmed mean robust to outliers",
            },
            ".internal_winsorize": {
                "params": ["vec", "fraction = 0.05"],
                "export": False,
                "doc": "Internal helper for winsorization",
            },
        }
        self.lockfile = {
            "R": {"Version": "4.3.3"},
            "Packages": {
                "rlang": {"Version": "1.1.3", "Source": "CRAN", "Hash": "a1b2c3d4"},
                "vctrs": {"Version": "0.6.5", "Source": "CRAN", "Hash": "e5f6g7h8"},
                "testthat": {"Version": "3.2.1", "Source": "CRAN", "Hash": "99aabbcc"},
            },
        }

    def simulate_roxygen(self) -> None:
        header("1. devtools::document() [roxygen2]")
        step_print(1, "Parsing roxygen tags (@export, @param, @return)...")
        time.sleep(0.3)

        exported_syms = []
        for name, meta in self.functions.items():
            if meta["export"]:
                exported_syms.append(name)
                print(f"  {GREEN}ℹ Writing man/{name}.Rd{RESET}")
                print(f"    {DIM}* Title: {meta['doc']}{RESET}")
                print(f"    {DIM}* Parameters: {', '.join(meta['params'])}{RESET}")
            else:
                print(f"  {YELLOW}ℹ Skipping internal symbol '{name}' (no @export){RESET}")

        print(f"\n{BOLD}Generated NAMESPACE file:{RESET}")
        print(f"{DIM}# Generated by roxygen2: do not edit by hand{RESET}")
        for sym in exported_syms:
            print(f"{CYAN}export({sym}){RESET}")
        print(f"{CYAN}import(rlang){RESET}")
        print(f"\n{status_badge('Documentation & NAMESPACE up-to-date')}\n")

    def simulate_testthat(self) -> bool:
        header("2. devtools::test() [testthat 3e]")
        step_print(1, "Testing package 'faststats' in clean sub-process...")
        time.sleep(0.4)

        tests = [
            ("test-trim-mean.R", "calculate_trim_mean works on standard vector", True, "expect_equal(result, 5.0)"),
            ("test-trim-mean.R", "calculate_trim_mean handles NA values when na_rm=TRUE", True, "expect_equal(result, 5.0)"),
            ("test-trim-mean.R", "calculate_trim_mean errors on non-numeric input", True, 'expect_error(..., class = "vctrs_error_incompatible_type")'),
            ("test-trim-mean.R", "calculate_trim_mean rejects invalid trim fraction", True, "expect_error(..., regexp = 'trim must be between 0 and 0.5')"),
        ]

        all_ok = True
        print(f"{BOLD}{WHITE}✔ | F W S  OK | Context{RESET}")
        for test_file, desc, passed, code in tests:
            time.sleep(0.2)
            if passed:
                print(f"{GREEN}✔{RESET} | {DIM}0 0 0{RESET}   1 | {test_file}: {desc}")
                print(f"    {DIM}↳ Passed: {code}{RESET}")
            else:
                all_ok = False
                print(f"{RED}✖{RESET} | 1 0 0   0 | {test_file}: {desc}")
                print(f"    {RED}↳ Failure: {code}{RESET}")

        print(f"\n{BOLD}{'='*40}{RESET}")
        if all_ok:
            print(f"{BOLD}{GREEN}[ PASS 4 | WARN 0 | SKIP 0 | FAIL 0 ]{RESET}")
            print(f"{status_badge('testthat suite passed successfully', True)}")
        else:
            print(f"{BOLD}{RED}[ FAILURES DETECTED ]{RESET}")
        return all_ok

    def simulate_rcmd_check(self) -> None:
        header("3. R CMD check (devtools::check())")
        checks = [
            ("Checking DESCRIPTION meta-data", "OK", True),
            ("Checking for non-standard license specification", "OK", True),
            ("Checking NAMESPACE compatibility with R/ code", "OK", True),
            ("Checking code syntax and global variable usage (no visible binding)", "OK", True),
            ("Checking documentation \\usage consistency with function args", "OK", True),
            ("Checking examples in man pages", "OK", True),
            ("Running testthat test suites in sub-architecture", "OK", True),
            ("Checking package vignettes rendering (Rmarkdown/knitr)", "NOTE: No vignettes found.", "NOTE"),
        ]

        for desc, res, status in checks:
            time.sleep(0.2)
            if status is True:
                print(f"* {desc} ... {GREEN}OK{RESET}")
            elif status == "NOTE":
                print(f"* {desc} ... {YELLOW}NOTE{RESET}")
                print(f"  {YELLOW}* Suggestion: Consider adding at least one introductory vignette.{RESET}")
            else:
                print(f"* {desc} ... {RED}ERROR{RESET}")

        print(f"\n{BOLD}R CMD check results:{RESET}")
        print(f"  {BOLD}{GREEN}0 errors ✔{RESET} | {BOLD}{GREEN}0 warnings ✔{RESET} | {BOLD}{YELLOW}1 note ℹ{RESET}")
        print(f"{status_badge('Package passes CRAN baseline criteria')}\n")

    def simulate_renv(self) -> None:
        header("4. renv (Reproducible Environments)")
        print(f"{DIM}Simulating renv::status() & renv::snapshot()...{RESET}")
        time.sleep(0.3)

        print(f"\n{BOLD}Current Lockfile state (renv.lock):{RESET}")
        print(f"{CYAN}{json.dumps(self.lockfile, indent=2)}{RESET}")

        step_print(1, "Auditing installed libraries vs lockfile...")
        time.sleep(0.3)
        print(f"  {GREEN}✔ rlang [1.1.3] matches lockfile hash.{RESET}")
        print(f"  {GREEN}✔ vctrs [0.6.5] matches lockfile hash.{RESET}")
        print(f"  {GREEN}✔ testthat [3.2.1] matches lockfile hash.{RESET}")
        print(f"\n{status_badge('Environment is synchronized and fully reproducible')}\n")

    def simulate_targets(self) -> None:
        header("5. targets Pipeline Execution (Make-like Reproducibility)")
        print(f"{DIM}Parsing _targets.R DAG (Directed Acyclic Graph)...{RESET}\n")

        pipeline_nodes = [
            ("raw_data_file", "data/raw_experiment.csv", "Up to date (hash match)"),
            ("cleaned_data", "clean_dataset(raw_data_file)", "Cached [0.12s]"),
            ("summary_stats", "calculate_trim_mean(cleaned_data$val)", "Cached [0.04s]"),
            ("final_report", "tar_render(report, 'report.Rmd')", "Dispatched & Rebuilt [0.85s]"),
        ]

        for target, expr, action in pipeline_nodes:
            time.sleep(0.3)
            icon = "✔" if "Cached" in action or "Up to date" in action else "▶"
            color = GREEN if icon == "✔" else MAGENTA
            print(f"  {color}{icon} target {target}{RESET}")
            print(f"    {DIM}Command: {expr}{RESET}")
            print(f"    {DIM}Action : {action}{RESET}\n")

        print(f"{status_badge('targets::tar_make() pipeline completed in 1.01s')}\n")


def interactive_menu():
    sim = RPackageSimulator()
    while True:
        print(f"{BOLD}{BG_BLUE}{WHITE}  R PACKAGE DEV & REPRODUCIBILITY LAB (BAB-09)  {RESET}")
        print(f"{BOLD}Pilih simulasi teknis yang ingin dijalankan:{RESET}")
        print("  1. devtools::document() [Roxygen2 & NAMESPACE]")
        print("  2. devtools::test() [testthat unit tests]")
        print("  3. devtools::check() [R CMD check automated audit]")
        print("  4. renv::status() & lockfile verification")
        print("  5. targets::tar_make() pipeline DAG execution")
        print("  6. Run Complete End-to-End Pipeline")
        print("  0. Keluar")

        try:
            choice = input(f"\n{BOLD}{CYAN}Masukkan pilihan (0-6): {RESET}").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nExiting.")
            break

        if choice == "1":
            sim.simulate_roxygen()
        elif choice == "2":
            sim.simulate_testthat()
        elif choice == "3":
            sim.simulate_rcmd_check()
        elif choice == "4":
            sim.simulate_renv()
        elif choice == "5":
            sim.simulate_targets()
        elif choice == "6":
            sim.simulate_roxygen()
            sim.simulate_testthat()
            sim.simulate_rcmd_check()
            sim.simulate_renv()
            sim.simulate_targets()
            print(f"{BOLD}{GREEN}*** Seluruh alur Package Development & Reproducibility Selesai! ***{RESET}\n")
        elif choice == "0":
            print(f"{BOLD}{YELLOW}Terima kasih. Sesi lab selesai.{RESET}")
            break
        else:
            print(f"{RED}Pilihan tidak valid. Silakan pilih 0-6.{RESET}\n")


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--all":
        # Non-interactive automated execution
        runner = RPackageSimulator()
        runner.simulate_roxygen()
        runner.simulate_testthat()
        runner.simulate_rcmd_check()
        runner.simulate_renv()
        runner.simulate_targets()
    else:
        interactive_menu()
